### ISSUE TITLE
dependencies not automatically installed

### ISSUE THREAD

**Issue by GrayAlex49** [daattali/timevis#10]
When installing from CRAN, timevis does not automatically install xtable if it is not present but then fails to load if its not installed.  I know several other packages automatically install their dependencies on install if needed.

**Comment by daattali** [comment]
I didn't think xtable was required at all for the package. Are you getting errors during timevis installation? Or while trying to use the package?

**Comment by GrayAlex49** [comment]
While trying to load the package.  It loaded fine after I installed xtable 

package ‘timevis’ successfully unpacked and MD5 sums checked

>The downloaded binary packages are in
	C:\Users\----\AppData\Local\Temp\Rtmp40NmIe\downloaded_packages
> library(timevis)
Error : .onLoad failed in loadNamespace() for 'timevis', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: there is no package called ‘xtable’
Error: package or namespace load failed for ‘timevis’
> install.packages("xtable")
Installing package into ‘C:/Users/----/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/xtable_1.8-2.zip'
Content type 'application/zip' length 710068 bytes (693 KB)
downloaded 693 KB
package ‘xtable’ successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\Users\----\AppData\Local\Temp\Rtmp40NmIe\downloaded_packages
> 
> library(timevis)

**Comment by daattali** [comment]
I just installed a brand new version of R with absolutely no packages installed, and tried installing timevis. It does look like xtable was one of the packages it installed. I guess it's a dependency of some other package.  Maybe it was a one time random error that happened to you that won't happen again?

```
> install.packages("timevis")
also installing the dependencies ‘stringi’, ‘magrittr’, ‘formatR’, ‘highr’, ‘markdown’, ‘stringr’, ‘bitops’, ‘digest’, ‘Rcpp’, ‘yaml’, ‘knitr’, ‘caTools’, ‘evaluate’, ‘base64enc’, ‘httpuv’, ‘mime’, ‘xtable’, ‘R6’, ‘htmltools’, ‘htmlwidgets’, ‘jsonlite’, ‘rmarkdown’, ‘shiny’
```

**Comment by GrayAlex49** [comment]
Well thats weird, thank you for checking it out.

**Comment by daattali** [comment]
Thanks for reporting :)
