### ISSUE TITLE
Duplicated output in xaringan

### ISSUE THREAD

**Issue by gavg712** [daattali/timevis#105]
Hi,

 I am trying to add timevis to a xaringan presentation, but it appears as duplicated html widget. Zoom control works with second timevis, and both are interactive. 

![timevis output in xaringan](https://user-images.githubusercontent.com/8514904/102944881-15644300-448a-11eb-80f5-3065ef2674e7.png)

I started here after reviewing the documentation for `timevis`, `xaringan` and `htmlwidgets`. I didn't find a explanation for this issue. However, I don't rule out an incompatibility of xaringan with htmlwidgets. Anyway, I give a reproducible example:

```
---
title: "timevis reproducible"
date: "2021/01/04 (actualizado: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, default-fonts, "style_tv.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Testing timevis

```{r echo=FALSE}
library(tidyverse)
library(timevis)
tl_template <- function(date, name, event, fa_icon) {
  glue::glue(
    '<div class="wrapper">{icon} <b>{date} | {name}</b>
    <div class="tooltip">{event}</div></div>',
    date = date, 
    name = name, 
    event = event, 
    icon = fontawesome::fa(name = fa_icon, fill = "darkgreen")
  )
}

data <- read_csv("gis_history.csv") %>% 
  transmute(id = row_number(),
            start = as.character(datetime),
            content = pmap(list(date_label, name, event, icon), tl_template))

timevis(data, width="100%", height = "200px",loadDependencies = FALSE, showZoom = TRUE)
```
<sub>Data retrieved from [timetoast](https://www.timetoast.com/timelines/historia-de-los-sistemas-de-informacion-geografica-sig)</sub>

Thank you in advance

Gabo Gaona

``` r
sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.1 LTS
#> 
#> Matrix products: default
#> BLAS/LAPACK: /opt/OpenBLAS/lib/libopenblas_haswellp-r0.3.10.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=es_EC.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=es_EC.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=es_EC.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=es_EC.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] timevis_1.0.0   forcats_0.5.0   stringr_1.4.0   dplyr_1.0.2     purrr_0.3.4     readr_1.4.0    
#>  [7] tidyr_1.1.2     tibble_3.0.4    ggplot2_3.3.2   tidyverse_1.3.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.0.3  magrittr_2.0.1  tools_4.0.3     htmltools_0.5.0
#>  [5] yaml_2.2.1      stringi_1.5.3   rmarkdown_2.6   highr_0.8      
#>  [9] knitr_1.30      stringr_1.4.0   xfun_0.19       digest_0.6.27  
#> [13] rlang_0.4.9     evaluate_0.14
```

<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

[test.zip](https://github.com/daattali/timevis/files/5732613/test.zip)

**Comment by daattali** [comment]
Hi @gavg712 thanks for the deatailed bug report. I'll leave this issue open but I don't think I myself will get around to it as I've never used xaringan and I'm not familiar at all with how it works. Maybe someone who understands xaringan better and has an hour to kill some time can help look into this.

**Comment by gavg712** [comment]
Thank you @daattali.
In order to provide more details. I tested in different ways with you examples and my example. I found, this happens only on the first `timevis` object call, subsequent calls are shown as correct.

The immediate solution I found is call a first time in a CSS class `hide` in a previous slide and then call the target timevis objetc in the corresponding slide

For instance, my temporal solution in case someone need:

### In custom_style.css file

```css
.hide{
  display: none;
}
``` 

### In a previuos slide of xaringan Rmarkdown file 

```
.hide[
` ` `{r echo=FALSE}
 timevis(data, loadDependencies = FALSE, showZoom = FALSE, )
` ` `
]
```

**Comment by daattali** [comment]
Thanks for sharing!

**Comment by daattali** [comment]
I really think this is a xaringan bug. When trying to come up with a minimal reproducable example, I see that the following code **works**:

````
---
output: xaringan::moon_reader
---

# Testing timevis

```{r echo=FALSE}
timevis::timevis(timevis::timevisData, width = "100%")
```
````


But if I add a YAML title so that there is now a cover page, the timevis is duplicated:

````
---
title: "test"
output: xaringan::moon_reader
---

# Testing timevis

```{r echo=FALSE}
timevis::timevis(timevis::timevisData, width = "100%")
```
````

**Comment by gavg712** [comment]
Hi there. 
Sorry for long time without a reply. Yes, I tested as well. Seems a problem related with xaringan to support some htmlwidgets. The I will close the issue!
Thank you again!
