### ISSUE TITLE
Trying to add a second group on the secondary x axis that documents the date segments in quarters

### ISSUE THREAD

**Issue by kylegross** [daattali/timevis#108]
I'm trying to add a dataframe to the timevis that displays the project in quarters. The dates are the same across 16 different assets. The files will be too large if I add the quarter segments manually in each of the assets, so I wanted to reference the dataframe I created for the quarters to add them to the timeline. I cannot figure out how to do this. I essentially want to be able to separate the dates on the timeline into quarters.

![image](https://user-images.githubusercontent.com/67433011/106032007-ed29be80-609d-11eb-9e8a-e920f95be86f.png)

**Comment by daattali** [comment]
The {timevis} package is a binding to a javascript library, and I don't know if this is a supported feature of the library. You can look at the [official docs](https://visjs.github.io/vis-timeline/docs/timeline/) to see how to do this.

**Comment by kylegross** [comment]
got it, thank you.
