### ISSUE TITLE
Sum columns in timevis

### ISSUE THREAD

**Issue by kylegross** [daattali/timevis#109]
Hi there,

I am trying to sum columns in the timevis timeline, which would be responsive when different assets in the timeline are moved. 

![image](https://user-images.githubusercontent.com/67433011/106503690-f945bf80-6493-11eb-8a93-f31f4d7aaa65.png)

The numbers in each box on the timeline show the cost of that specific phase, and I need a way to get the total sum per various timeframes (for instance, per month). Is that possible?

In addition, I need to edit the timeline zoom so that it does not show times, so the lowest level when zooming is the day. I also need to change the timeline format so that the dates are shown as m-d-y, but when I edited your prettyDate function, no changes to the format are displayed. If you have any ideas on how to edit these two things, as well as adding the summation to the timevis, that would be very helpful.

**Comment by kylegross** [comment]
Figured out the zoom issue.

**Comment by kylegross** [comment]
Odd, but I finally got the timedate format to change. Not sure why it wouldn't work before. Now I just need help on the column summation.

**Comment by daattali** [comment]
The timeline is simply a visualization. It doesn't do anything fancy with the data other than return to you the data as a dataframe. You'll need to write a custom function for extracting the times you're intereted in and doing the math, there's no magic function for it.
