### ISSUE TITLE
How to overlap points and ranges, and remove content labels?

### ISSUE THREAD

**Issue by cristobalcar** [daattali/timevis#110]
Hi, I wanted to know if it's possible to do this...
This is what I have now
![image](https://user-images.githubusercontent.com/29803674/107058244-20adcc80-67b3-11eb-9a37-01f261ae7612.png)

This is what I want to get.... overlap and no content labels
![image](https://user-images.githubusercontent.com/29803674/107129710-0dc7f480-68a6-11eb-95c5-181aae1c1b8a.png)

Thank you!

Cristobal

**Comment by daattali** [comment]
I don't know if that's supported. Please see the documentation for the u deploying javascript library https://visjs.github.io/vis-timeline/docs/timeline/  to see if this feature is supported
