### ISSUE TITLE
showWeekScale not showing scale

### ISSUE THREAD

**Issue by jaleds** [daattali/timevis#113]
I have just started using timevis() - very nice package :-)
However I would like to have a week-scale, but cannot get it to work
`timevis(
  data.frame(id = 1:2,
             content = c("one", "two"),
             start = c("2016-01-10", "2016-01-12")),
  options = list(showWeekScale = TRUE)
)
`
![timevis - showWeekScale](https://user-images.githubusercontent.com/56019160/112729783-37101300-8f2e-11eb-9fe1-192500214812.png)

**Comment by daattali** [comment]
This package is using visjs timeline version 4.16.1. Are you sure this feature exists in that version?

**Comment by jaleds** [comment]
I found the option in [visjs-doc](https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options)
I have not been able to find out which version it works in.  
Do you have any plans to upgrade the package to the newest visjs-version?

**Comment by daattali** [comment]
You'll have to look through the releases of visjs or their changelog or do a big of investigating to find out what version it was added to.

For plans to update, see issue #50

**Comment by daattali** [comment]
visjs hsa been updated so this should work now

**Comment by jaleds** [comment]
Thanks daattali now it is working :-)

For EU users, locales is a bit tricky refer to [visjs weekStyling](https://visjs.github.io/vis-timeline/examples/timeline/styling/weekStyling.htmll). Is you want english language then you are forced to use USWeek and not ISOweeks. 

timevis with locale
`timevis( data.frame(id = 1:2, content = c("one", "two"), start = c("2021-09-01", "2021-10-01")), 
         options = list(showWeekScale = TRUE, locale="en")) 
`

If you want to use ISO week then you have to choose "nl", "de", "fr" or "it" as label language.
I have tried to use "da" (danish) - the language is not supported. 
In most EU countries ISOweek and english language is preferred. However I cannot see that the combination is supported in visjs.  
I prefer that "en" is used for global english language with ISO as standard calculation. If local is "us" then US week can be used. However it is better to split standard calculation and language.
