### ISSUE TITLE
feature inquiry: enabling and visualizing event dependencies

### ISSUE THREAD

**Issue by erstearns** [daattali/timevis#120]
Thank you so much for creating this great package! Projects often have tasks with dependencies that influence the timeline. Is there currently a way for timevis to take that into account? For example, if you need to reproject a dataset prior to running an analysis on it, is there a way in timevis to link these 2 events such that if the 'reproject dataset' event gets delayed, the 'running analysis' event automatically gets pushed back as well at the same interval as the delay?  In addition to this action, is there a way to visualize the dependencies (e.g. with lines between events, similar to [this Asana visualization](https://blog.asana.com/2018/07/asana-timeline-draw-dependencies-between-tasks/)). Thank you!

**Comment by daattali** [comment]
This package (or rather, the underlying javascript library that powers it) does not support linking events, at least not to my knowledge. The complete documentation for the underlying library is here https://visjs.github.io/vis-timeline/docs/timeline/ -- I'm not familiar with everything it can do, as my package is simply a middleman. If you can see this feature in their documentation, then it should be possible with {timevis}
