### ISSUE TITLE
feature inquiry: Change rectangles to other objects

### ISSUE THREAD

**Issue by Hojnicki** [daattali/timevis#121]
Thank you for creating this incredibly useful package. Quick Question: Is there any way to modify specific rectangular boxes to other shapes? For example, perhaps I want to show events on a timeline as standard rectangles, but I want to show decision points as a star or something other. How would I go about changing the shape? (I understand I could potentially add an icon inside the rectangle like your world cup example, looking for something else) Thank you

**Comment by daattali** [comment]
You'll have to look at the documentation for the underlying javascript library to see if this is possible. Their documentation is at https://visjs.github.io/vis-timeline/docs/timeline/

If it's possible to do there, then it would very likely be possible to replicate with {timevis}. This package only provides a binding to the javascript library and I can support any issues with this package, but I can't provide support for how to use the underlying library.
