### ISSUE TITLE
 language error

### ISSUE THREAD

**Issue by 13479776** [daattali/timevis#124]
Dear daattali,

I used the timevis, but the language is error. I would like to ask for help how to change it into english?  Thanks. My location is China

![image](https://user-images.githubusercontent.com/19190576/190064273-1b809cf7-391e-4d55-b383-a056f336cb3e.png)

Hees

**Comment by daattali** [comment]
Try `setOptions(list (locale = c("en"))`

**Comment by 13479776** [comment]
Great!  it works, Thank you

hemi

**Comment by daattali** [comment]
I don't know why it does that to begin with, someone else reported that last week. Strange.
