### ISSUE TITLE
Using observeEvent causes rendering issues

### ISSUE THREAD

**Issue by AdamMJenks** [daattali/timevis#13]
When utilizing observe event for a submission to look at a subset of a possible `renderTimevis`, after the first selection each new subset selected to view adds additional entries above the existing selection rather than overwriting and clearing the previous selection.

**Comment by daattali** [comment]
Can you provide a small reproducible example? I haven't run into this issue myself so I'll need to see it

**Comment by daattali** [comment]
Closing because no example was given
