### ISSUE TITLE
Online demo license expired

### ISSUE THREAD

**Issue by axelvugts** [daattali/timevis#131]
I just noticed that the online timevis demo at https://daattali.com/shiny/timevis-demo/ is not working because of a licensing problem. It would be great for newcomers like me if you could have a look at this issue :)
```
Your Shiny Server license expired on February 8, 2023.

Please purchase and activate a license.
```

**Comment by daattali** [comment]
Thanks. I'll have to repurchase a license this week. This will resolve next week.

**Comment by daattali** [comment]
It's back up
