### ISSUE TITLE
timeline-arrows package

### ISSUE THREAD

**Issue by Nefcairon** [daattali/timevis#133]
Hello,

First, thanks for creating this wrapper to vis.js.

For vis.js someone has created an addon that allows to create arrows between items: https://github.com/javdome/timeline-arrows

This is especially great for creating gantt charts.

Could you consider adding this functionality? Sadly I am not able to create this myself.

**Comment by daattali** [comment]
That would be an entirely new package, it's not a small feature to add. It's very cool, but out of scope for this package.
