### ISSUE TITLE
Changing language in the viewer

### ISSUE THREAD

**Issue by jusmendonca** [daattali/timevis#135]
Thanks a lot for the package! Excuse my ignorance, but how could I change the language for the months of the year in the viewer?

**Comment by daattali** [comment]
I'm not sure. By looking at the documentation for visjs Timeline https://visjs.github.io/vis-timeline/docs/timeline/#Localization it seems like changing languages is not supported out-of-the-box, but it can be done by loading an additional javascript file and changing the configuration. I can't help with that, you'll need to read their documentation and apply the same instructions here (this means you need to be familiar with javascript and how to import javascript files)
