### ISSUE TITLE
On which version of visjs-Timeline is Timevis running?

### ISSUE THREAD

**Issue by rrodrigueznt** [daattali/timevis#137]
Hi! I'm enjoying this elegant piece of software a lot! Thanks for your work, @daattali!

I'm struggling to understand its functioning. The last reference I found to **visjs-Timeline** in the development workflow is [visjs-Timeline](https://github.com/daattali/timevis/commit/97fbd7bf566ff6605e18035c1c8ac8b52af181e7)

Please, is this the actual last one? Is **Timevis** currently running on **visjs-Timeline** `version 7.4.9`? How could I know it by inspecting **Timevis** code?

Thanks!

**Comment by daattali** [comment]
7.4.9, you can see it here https://github.com/daattali/timevis/tree/master/inst%2Fhtmlwidgets%2Flib
