### ISSUE TITLE
name of the month is an abbreviation in Ukrainian

### ISSUE THREAD

**Issue by longhua8800w** [daattali/timevis#141]
The name of the month is an abbreviation in Ukrainian, how to change it into an abbreviation in English or other languages?

<img width="728" alt="image" src="https://github.com/daattali/timevis/assets/19342379/a97d5900-9b3a-4daa-b61e-a0688bb0ead6">

**Comment by daattali** [comment]
There's a few issues open for this, for example https://github.com/daattali/timevis/issues/124
