### ISSUE TITLE
Crosstalk error: Error: timevis: 'data' must be a data.frame

### ISSUE THREAD

**Issue by jennyv0** [daattali/timevis#142]
Hello! Love the package.

I'm trying to get the crosstalk functionality to work but I am getting hit with this error when trying to run the demo app, and also the following code snippet from the documentation: 

`Error: timevis: 'data' must be a data.frame`

It doesn't seem to want to accept the `shared_df` object for some reason! Any ideas what the issue is?

Thanks :)

**Comment by daattali** [comment]
This feature is not on CRAN. Are you using the development version from github?

**Comment by jennyv0** [comment]
Ah yes indeed I was! Thank you so much!
