### ISSUE TITLE
No support for portuguese?

### ISSUE THREAD

**Issue by F-Chalreo** [daattali/timevis#144]
Hi, I think the package is amazing, but unfortunately it doesn't seem like there is an option to change the language to portuguese. I tried locale = "pt" and locale = "br" and none seem to work. Would you consider adding it as an option, or anyone has a workaround to solve it? Thank you,

**Comment by daattali** [comment]
Please refer to the full official documentation of the underlying javascript library (visjs timeline) https://visjs.github.io/vis-timeline/docs/timeline/

There's a section on localization there. The timevis package provides an easy way to bind to that javascript library, but it's out of scope for timevis to know how every feature of visjs timeline works.
