### ISSUE TITLE
addCustomTime (vertical bars) : Is it possible to set color / style?

### ISSUE THREAD

**Issue by marceluk** [daattali/timevis#15]
timevis is a fantastic addition to the htmlwidgets in R.

Is it possible to set color / thickness / type (eg. dashed) for the addCustomTime bar? If so how?

Marcel.

**Comment by daattali** [comment]
Thank you! Unfortunately the javascript library powering timevis does not give such an option, you can see http://visjs.org/docs/timeline/ - addCustomTime only has time and id parameters.

If you're really keen on styling it, you can do that using custom CSS, but that's outside the scope of timevis

**Comment by daattali** [comment]
Thank you! Unfortunately the javascript library powering timevis does not
give such an option, you can see http://visjs.org/docs/timeline/ -
addCustomTime only has time and id parameters.

If you're really keen on styling it, you can do that using custom CSS, but
that's outside the scope of timevis

---
R-Shiny Consultant
http://deanattali.com/shiny
