### ISSUE TITLE
Integration of line charts and Graph2d

### ISSUE THREAD

**Issue by ThomasChln** [daattali/timevis#153]
Hi, 

Could we integrate functionality for line charts and Graph2d ? https://visjs.github.io/vis-timeline/examples/graph2d/
It uses the same vis.js timeline library. https://visjs.github.io/vis-timeline/

I forked your repo here https://gitlab.com/thomaschln/linevis
I renamed as linevis and made the necessary changes. The example shiny app works fine, it is based on this example https://visjs.github.io/vis-timeline/examples/graph2d/01_basic.html 

I hastily copied and replaced but it's good enough for my current use.
We can either integrate this functionality in timevis, or I can continue development as an independent package.
Since it uses the same JS file I thought it would make sense to integrate it here.

Thanks

**Comment by daattali** [comment]
Hi Thomas
Thanks for the initiative. I thought about it a little bit and even though it uses the same source, the two are essentially very different. Timevis is already cemented as a timeline visulization, and adding the Graph2d into this package feels like overloading the package. I think it would be a great candidate for an independent package, and you are very welcomed to use the code here to continue developing the other package. Good luck with linevis! :)

**Comment by ThomasChln** [comment]
linevis is now available on CRAN :)
https://cran.r-project.org/package=linevis
