### ISSUE TITLE
example of custom css?

### ISSUE THREAD

**Issue by Myfanwy** [daattali/timevis#18]
Hi there,

Thanks for the great R package!  I can't find the code used to create the sample data in the "slightly more advanced examples" section of the vignette - specifically I'm having trouble formatting my own dataframe with the css components in the `className` and `style` columns to make it look like the png in the vignette (or something like it).  Can you point me to where the code that includes the css is?

Thanks so much,
Myfanwy

**Comment by daattali** [comment]
The exact code that the app uses is [here](https://github.com/daattali/timevis/tree/master/inst/example)

You can see the css file that it uses (specifically look for the rules for "#timelineCustom") to see some of my css, or you can look at the [sampleData](https://github.com/daattali/timevis/blob/master/inst/example/sampleData.R) file there to see the dataframes I use

**Comment by Myfanwy** [comment]
I'm really apologize, but I'm still not understanding - I did look through all the code in inst/example prior to opening the issue, I just couldn't pinpoint the css used to create [this timeline](https://github.com/daattali/timevis/blob/master/inst/img/customstyle.png).  

Did it come from [this css file](https://github.com/daattali/timevis/blob/master/inst/example/www/style.css), and if so, how should I link to a stylesheet in the `timevis` function?

**Comment by daattali** [comment]
Yes it did come from that css file. You link to the css file from the ui. You can look at the ui code and see it makes a reference to the css file. You do need to know how to use css in shiny in order to do this, timevis is not meant to teach you css. I suggest you Google for "R shiny css" if you don't understand how to include css.

**Comment by daattali** [comment]
Even if you want to just take a screenshot and you don't need shiny, it
might be easier to customize the appearance using a css file in shiny. You
can try to copy all the files in the example, substitute your data, and
play with the existing css file.  Easier to use existing working code then
to start from scratch

**Comment by Myfanwy** [comment]
That's really helpful, I'll start there!  Thanks again.

**Comment by HOHOOO** [comment]
I have the same problem, thank u for your suggestion!
