### ISSUE TITLE
no package called 'stringi'

### ISSUE THREAD

**Issue by deanhardy** [daattali/timevis#28]
Rad idea! Thanks for working on this! Getting this error:

`library(timevis)
timevis()`

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’``

**Comment by daattali** [comment]
stringi is not even a direct dependency of timevis so that's strange. Looks
like when you installed timevis the dependencies didn't get installed. Trey
installing stringi (or better yet, reinstall timevis with the dependencies
flag set to TRUE)

**Comment by deanhardy** [comment]
I don't know what I'm doing so much, but I did check the dependencies box... I think.

That said, I installed stringi separately and it works now. Thanks for the rapid reply!
