### ISSUE TITLE
subgroupOrder syntax

### ISSUE THREAD

**Issue by deanhardy** [daattali/timevis#29]
Not so much an issue, but I'm curious what the syntax is for the subgroupOrder argument. I haven't seen it in the code here or in the help via ?timevis(). Thanks.

**Comment by daattali** [comment]
Take a look at the timeline JS library example of using subgroupOrder
http://visjs.org/examples/timeline/groups/subgroups.html (you'd have to look at the source of that webpage to see the javascript configuration that resulted in that. Once you see the JS configuration, try to mimic the same object in R - I think it'll mean just adding another column to the groups dataframe)

If you look at that example and still can't figure it out, please post your question on stackoverflow and link me to it, and I'll try to answer when I can
