### ISSUE TITLE
When re-rendering a timeline, the old data are not removed

### ISSUE THREAD

**Issue by daattali** [daattali/timevis#3]
Bug reported to me via private email.

Example:

```
library(shiny)
library(timevis)

ui <- fluidPage(
  timevisOutput("timeline"),
  textInput("text", "Text", "Hello")
)

server <- function(input, output, session) {
  output$timeline <- renderTimevis(
    timevis(data.frame(start = Sys.Date(), content = input$text))
  )
}

shinyApp(ui = ui, server = server)
```

Every time you change the text, a new item gets added but all the previous ones still exist. That's a clear bug and not how it should work.

**Comment by hemans** [comment]
I recently installed timevis but face the same problem though it states as solved and closed? 
Would appreciate the help to fix it.

Thanks

**Comment by daattali** [comment]
did you install from CRAN or from GitHub?  Please show a minimal reproducible example

**Comment by daattali** [comment]
Did you install from CRAN or github?  The CRAN version isn't updated.

**Comment by hemans** [comment]
Thanks for the response. I reinstalled from github and its working fine.

Thanks
