### ISSUE TITLE
Fix: Timeline does not render in Safari

### ISSUE THREAD

**Issue by emillykkejensen** [daattali/timevis#30]
I had some problems with the timeline, not rendering in Safari and turns out, that the new version fixes that. So consider updating to vis v. 4.19.1.

**Comment by daattali** [comment]
Noted. I remember trying to update a couple months ago and noticing some other regressions bugs so I held off. I'll take a look again later, thanks!

**Comment by daattali** [comment]
related to #32

**Comment by daattali** [comment]
related to #50

**Comment by daattali** [comment]
This will be fixed once I can update to the latest version (which currently has some regression bugs)
