### ISSUE TITLE
Group Color

### ISSUE THREAD

**Issue by sageknight** [daattali/timevis#31]
Not really an issue but a cool feature I think might be useful. Suppose in our data we have 2 categorical columns, 1 can be grouped as row label as of now, wouldn't it be great if the other one can be shown using color-coding, that is, data in the same group appear in the same color. It would add another dimension to our visualization tool.

It looks something like this
![example](https://cloud.githubusercontent.com/assets/10823747/24951953/3ca8a676-1fa0-11e7-8901-e6ffe4763a71.PNG)

**Comment by daattali** [comment]
Is this supported in the javascript library? Here are the full docs: http://visjs.org/docs/timeline/

If it's not implemented in the library, then it likely won't be supported in timevis (which is essentially just an R binding to it)

**Comment by sageknight** [comment]
I read through the document and I don't think it's implemented in JS. Thanks for your answer.

**Comment by daattali** [comment]
In that case it won't be in timevis unfortunately
