### ISSUE TITLE
Group colours

### ISSUE THREAD

**Issue by p-phillips** [daattali/timevis#35]
Is it possible to have a column in the dataframe or an argument to timevis which affects the colour of the bars and points ?   I've tried the 'style' argument, but that only affects the label on the LHS of the graph.

My preference would really be to have an argument that allowed timevis to select the colours automatically depending on the number of groups and assign them itself.

Cheers
Pete

**Comment by daattali** [comment]
Hello

Please take a look at the official documentation of the underlying
javascript library visjs.org/docs/timeline/

I don't know it this feature is supported by the library. If not, then it
sill not be possible. Timevis only provides bindings to ther library, bit I
do not want to start adding new features to their lib.
