### ISSUE TITLE
Group Order

### ISSUE THREAD

**Issue by gamaly** [daattali/timevis#37]
I'm struggling with ordering groups. I've used the following syntax to order my data.frame alphabetically by country name. 

`Data <- Data[order(Data$Country), ])`

However, when displaying the groups, only some, but not all groups are displayed alphabetically. I'd say it gets about 90% correct.

I also looked at the JS documentation and found groupOrder, but haven't figured out how to implement that.

Any advice would be helpful. Thanks!

**Comment by daattali** [comment]
I haven't tried using a group order before. Looking at the docs, it says 

```
Order the groups by a field name or custom sort function. By default, groups are ordered by a property order (if set). If no order properties are provided, the order will be undetermined.
```

Have you tried adding an 'order' column?

**Comment by gamaly** [comment]
That seems to have worked! Thanks for the advice on that one, and for all of your hard work in general.
