### ISSUE TITLE
is it possible to use hover

### ISSUE THREAD

**Issue by sachinbanugariya** [daattali/timevis#38]
hello,
we implemented gantt chart using timevis,
we having some question.
> is it possible to hover method for task name's display when hover anywhere inside task bar?
> is it possible to see output at every bar end side and multiple values seems for one output ?
> is it possible to set some different color as per different categories. 

we really need this two things if possible then let us know ASAP, that how can we implement this.
Thanks.

**Comment by daattali** [comment]
Hello, I don't think any of these things are supported *natively*, but it's possible you can achieve them with some javascript and/or CSS. I should note that this package is mostly just binding to a javascript library that I have not written, so you may want to look at that library. It may be helpful to look at their [documentation](http://visjs.org/docs/timeline/) or at their [examples](http://visjs.org/timeline_examples.html)
