### ISSUE TITLE
vis.map not found

### ISSUE THREAD

**Issue by greg-minshall** [daattali/timevis#48]
with a running timeline, if i open the "web inspector" (developer console), i see a message:
`Failed to load resource: the server responded with a status of 404 (Not Found)`
for the file "lib/vis-4.16.1/vis.map".  if i add this file (from the vis.js distribution), this error message (which is probably indicative of nothing major) goes away.  cheers!

**Comment by greg-minshall** [comment]
i forgort to mention: e.g., https://daattali.com/shiny/timevis-demo/ gives this error message.

**Comment by daattali** [comment]
Strange, I never get that error with timevis. Here's my js console on the page you linked:

![image](https://user-images.githubusercontent.com/952340/36433783-6058054e-162b-11e8-993c-c3c9c4936779.png)

I have nothing against adding the map file though. If some users are seeing this error but adding the map file made it disappear then I would accept a PR for it. Thanks for report!

**Comment by greg-minshall** [comment]
it's all way beyond my javascript, etc., knowledge.  is vis.map in your lib/vis-4.16.1/ directory?  vis.map, afaict, appears in a comment
`lib/timeline-0.4/lib/vis-4.16.1/vis.min.js://# sourceMappingURL=vis.map`
so, maybe it's the console (in some mode i've randomly set it?) that is doing the lookup?
