### ISSUE TITLE
saving the timeline as png

### ISSUE THREAD

**Issue by sboriss** [daattali/timevis#55]
How can I save a timeline as a png file?

The following code did not work, the resulting file myTimeLine.png could not be opened.

myTimeline<-timevis(
         data.frame(id = 1:2,
                    content = c("one", "two"),
                    start = c("2016-01-10", "2016-01-12"))
     )
htmlwidgets::saveWidget(myTimeline, "myTimeLine.png", selfcontained = T)

**Comment by daattali** [comment]
I just looked at the savewidget function and it looks like it saves an html , not an image. I don't think what you're doing is supposed to work. There isn't a built in way to export as image (you'll find this is a common problem with most widgets). There are a few options mentioned in the timeline website that you can try: https://github.com/almende/vis/issues/2867

**Comment by daattali** [comment]
FYI you can now use my new package shinyscreenshot https://github.com/daattali/shinyscreenshot to take screenshots of a shiny app (or just part of a shiny app), and you cna use it to save a timevis as a PNG
