### ISSUE TITLE
Timevis and visNetwork still not playing nice in Shiny (all the time)

### ISSUE THREAD

**Issue by nklepeis** [daattali/timevis#61]
Hi All, 

I can run the Shiny+timevis+visNetwork app posted previously in related issues and see both types of output (using dataBasic data frame in example below).    However, using the attached data file (tdata) inside the timevis() call once again does not generate output.   

If you comment out the visNetworkOutput line, you will see the timeline.   The order of calling the output for timevis or visNetwork does not matter.   I am using timevis 0.4 and visNetwork 2.0.4 (latest releases) on Ubuntu 18.04 inside RStudio.

[tdata.zip](https://github.com/daattali/timevis/files/2560450/tdata.zip)

Any ideas?

--Neil

--------------------------------------------------------------
library(timevis)
library(shiny)
library(visNetwork)

nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

load(file="../tdata.Rdata")

print(tdata)

dataBasic <- data.frame(
  id = 1:4,
  content = c("Item one", "Item two" ,"Ranged item", "Item four"),
  start   = c("2016-01-10", "2016-01-11", "2016-01-20", "2016-02-14"),
  end    = c(NA, NA, "2016-02-04", NA)
)

ui<-fluidPage(
  timevisOutput('timeline'),
  visNetworkOutput('snagraph')

)

server<-function(input,output)({
  
  output$timeline<-renderTimevis(timevis(tdata))   
  output$snagraph<-renderVisNetwork(visNetwork(nodes,edges))

}
)

shinyApp(ui,server)

**Comment by daattali** [comment]
Note: even the `shiny` package itself was [observing problems](https://github.com/rstudio/shiny/pull/2359) when networkD3 was being used. That, together with the fact that timevis has not had issues with any other packages but has had multiple issues in the past when networkD3 was used, suggests to me that it's likely an issue caused by networkD3.
