### ISSUE TITLE
Imposible to disable double click

### ISSUE THREAD

**Issue by jpara3** [daattali/timevis#65]
I have issues to disable doubleclick using timevis. I have tried using 

timevis(datos,options=list(editable=TRUE,doubleClick=FALSE))

but it does not work

Thanks!

**Comment by daattali** [comment]
Hi @jpara3 , I wasn't aware of that option as something that should disable double clicking. Looking at the javascript documentation http://visjs.org/docs/timeline/ it looks like doubleClick is an *event*, but I don't see anywhere that says setting it to false will disable it
