### ISSUE TITLE
Feature request: allow timezone to be specified

### ISSUE THREAD

**Issue by daattali** [daattali/timevis#67]
By default, the timeline displays times in local time, but it's possible to use `moment.js` to specify it to show in a different timezone; see https://github.com/daattali/timevis/issues/66

**Comment by daattali** [comment]
@IkerrSC @jpara3 FYI

**Comment by jpara3** [comment]
What is intended to be is that the table that is shown in the timevis table gets the same time as the timeline shows.

Not sure if being able to enable 

        var options{
            moment: function(date){
                          return vis.moment(date).utc();

              }
          }


will be enought

**Comment by daattali** [comment]
As the documentation says, it's a parameter of timevis. `timevis(data, ..., timezone=1)`. It couldn't be used as an option because it required such specialized code, it's too much to expert a user to add `moment: function(date){return vis.moment(date).utc();}` so instead it's just a simple parameter

**Comment by jpara3** [comment]
I have tried with 

      timevis(data,.....,timezone=1) 

And I have get: 
      Unused argument timezone=1

I have tried also

      timevis(data,.....,timezone=1) 

And it did not work
Also I have tried adding 

      var options{
              moment: function(date){
                       return vis.moment(date).utc();

             }
          }

And also not working!

**Comment by daattali** [comment]
Did you install the latest version from github in the past 30 minutes?

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by daattali** [comment]
I tried installing the package just now on 3 different computers and did not have an issue. Try restarting your R session and reinstalling the package. 

If you still see a problem with timevis and you think there's a bug, please submit a new issue separate from this

**Comment by jpara3** [comment]
OK, 

Now its working but only if I set the timezone=0. With this there is no problem (but the data are shown with one hour of delay:
![imagen](https://user-images.githubusercontent.com/17548938/51300931-cad02580-1a2d-11e9-806b-215468d0444e.png)


But if I want to use a timezone, for example +1, then the timeline and the table show discrepancies:
![imagen](https://user-images.githubusercontent.com/17548938/51301004-010da500-1a2e-11e9-9b8f-a7e2be04c7b0.png)

**Comment by daattali** [comment]
What you're seeing is correct. For example, in the second example that you show, you're asking timevis to render as if it's in UTC+1, so in that timezone it's 00:00. If it's 00:00 in UTC+1, then in UTC it's 23:00. As I said a few times, **timevis can only return information to shiny in UTC** (that's what the Z means in the timestamp), so the return value of 23:00:00Z is correct because in UTC it is 23:00 when the timevis shows 00:00

**Comment by jpara3** [comment]
OK 

Thanks for all!
