### ISSUE TITLE
Input format for nestedGroups (if supported)

### ISSUE THREAD

**Issue by mstr3336** [daattali/timevis#68]
Hi, 
I noticed you discussed this a while back in #32 , but I couldn't really tell where you landed on it, whether it was an incorporated feature, or whether it could be done, but requires users to parse their list-cols to something json-friendly.
Could I please have some clarification on this?

Presently a list col, nestedGroups, seems to be coerced to this format: 
`"c(\"ID1\", \"ID2\")"`

~~If providing a string were to work, I'd assume that `'[ "ID1", "ID2"]'` might suffice~~

**Comment by mstr3336** [comment]
After investigating a little further, and looking at your attempts to deal with it, I see now that you did attempt a js-side fix by a little extra parsing, but didn't see much results and moved on.
The fix might be to force to-string coercion in R, and then parse it back into something .js friendly?

The other user mentioned having to mess up a bunch of your data checks to implement his version.
I will try this now, and see how it goes, anyway

**Comment by mstr3336** [comment]
Have forked and made a pull request

**Comment by mstr3336** [comment]
I closed it because it wasn't really working the way I expected.
I wound up modifying the `dataframeToD3` function to pass through nested list columns, which seems to have worked, kind-of. 
I don't see any nesting in my Rstudio output, nor chrome.
When I examine the source of the output widget, I see this:
** An example nested entry **
```js
{
            "group": "1:Ryde",
            "id": "L:7",
            "start": "1995-12-01 17:00:00",
            "end": "1995-12-04 11:00:00",
            "subgroup": "Ryde",
            "content": "W: Ward 2 RYD B: 5 Cat: NA L:7",
            "style": " font-size : 12pt;padding-bottom: 0px;",
            "pid": "1"
        }],
```
** The groups section ** 
```js
        "groups": [{
            "id": "1",
            "content": "1",
            "nestedGroups": ["1:Ryde", "1:Royal North Shore"]
        }, {
            "id": "2",
            "content": "2"
        }, {
            "id": "1:Ryde",
            "content": "1:Ryde"
        }, {
            "id": "1:Royal North Shore",
            "content": "1:Royal North Shore"
        }]
```

I'm not sure what I'm missing here, though. I'm not particularly experienced in js but I remember from one of your comments elsewhere that usually the tool aims to just pass all the data through to the relevant js library.
This data looks an awful lot like how nested group data should, though.
Do you have any ideas on this?

**Comment by daattali** [comment]
Looking at the [changelog of visjs](https://github.com/almende/vis/blob/master/HISTORY.md), it looks like nested groups was added in v4.18. I'm holding back on updating because of a few issues and I tried reaching out to the devs a few times to get them to address it. Feel free to bug them as well :)

**Comment by mstr3336** [comment]
Yeah, that was the magic bullet that made it work. 
I'll need to clean up my tree a bit before I make a pull request, as I added glue to suggests so I could use it for test error output. 
I immediately noticed those "issues" - with 4.21 RStudio's viewer seems to just give up entirely.
Also, the problem with folding on nests seems to be present.

**Comment by daattali** [comment]
This will be looked at again once #50 is done (which is stuck because visjs has still not fixed its regression bugs from a few years ago)
