### ISSUE TITLE
Ordering based on id

### ISSUE THREAD

**Issue by jamesLSI** [daattali/timevis#76]
Hi,

I'm trying plot individual project bars (grouped) with a single milestone point below it but despite my best efforts can't get them to order. I've tried order, and subgroupOrder but to no avail. I want it to render:
Project1
Milestone1
Project2
Milestone2

This code produces the most sensible outcome but still not quite right
timevis(ForGantt,
        groups = ganttGroups,
        width = 1750,
        options = list(order = htmlwidgets::JS('function(a, b) {
        return b.order - a.order;}')))

Any advice?

Thanks
James

**Comment by vjcitn** [comment]
+1 -- how do the events get ordered vertically within groups?  one would like earliest to start on the top by default, and could benefit from more control

**Comment by daattali** [comment]
I'm not sure what the logic is. You can refer to the official documentation of the underlying library to see what they say about this feature http://visjs.org/docs/timeline/

**Comment by rrodrigueznt** [comment]
> I'm not sure what the logic is. You can refer to the official documentation of the underlying library to see what they say about this feature http://visjs.org/docs/timeline/

Updated link to `visjs` documentation, https://visjs.github.io/vis-timeline/docs/timeline/

And URL to the page talking about items ordering, https://visjs.github.io/vis-timeline/examples/timeline/items/itemOrdering.html

Please, could anybody point us to an example to learn how to use `visjs` configuration options from `timevis`? Thanks!

**Comment by ThomasChln** [comment]
Thank you @rrodrigueznt for the URL to the page talking about items ordering.
In the HTML source of the page we can see Javascript code defined, and in particular 

```
  function customOrder (a, b) {
    // order by id
    return a.id - b.id;
  }

  // Configuration for the Timeline
  var options = {
    order: customOrder,
    editable: true,
    margin: {item: 0}
  };
```

Based on that I created the following R code, which works fine in my case (I preordered my `df_data` object)

```
    timevis::timevis(df_data, height = '100%', options = list(                  
                     order = htmlwidgets::JS("                                  
                       function customOrder (a, b) {                            
                         // order by id                                         
                         return b.id - a.id;                                    
                       }                                                        
                       ")))
```
