### ISSUE TITLE
No handler registered for type timeline_data:timevisDF

### ISSUE THREAD

**Issue by Quantumofcosmos** [daattali/timevis#78]
I am novice to both shiny and timevis. Tried to run example script given. The console gives the error when i try to access the app in viewer or browser. 

* code tried taken from [timevis demo](https://daattali.com/shiny/timevis-demo/)

## Error:
``` 
>> runApp('projects/oneoffMisc/shinytimvis.R')

Listening on http://127.0.0.1:6011
Warning: Error in <Anonymous>: No handler registered for type timeline_data:timevisDF
  [No stack trace available]
Error in (function (name, val, shinysession)  : 
  No handler registered for type timeline_data:timevisDF
```

What am I doing wrong?

**Comment by daattali** [comment]
Does timevis not work for you even in the most basic way?

**Comment by Quantumofcosmos** [comment]
The screen went grey (like something is overlayed) and it does not respond to click or scrolling.

The problem is now gone after I have updated RStudio to 1.2. Thank for all yo
