### ISSUE TITLE
Add multiple columns/groups in the timevis

### ISSUE THREAD

**Issue by anish-uchiha** [daattali/timevis#79]
I am using the timevis package to visualize timeline at region, country, status level.
While looking across online examples, I saw that most of them had only 1 group and timeline associated with that.

I wish to show multiple groups as different column headers and make timeline accordingly.
I hope it makes sense.
Any leads or clues will be highly appreciated.

Thanks and Regards,
Anish

![image](https://user-images.githubusercontent.com/20414758/60447429-13c51080-9c41-11e9-9059-e65b059d3d30.png)

**Comment by daattali** [comment]
Please look at the official documentation for the underlying javascript library https://visjs.org/docs/timeline/ that should show everything that's possible to do. The timevis package is mostly a connection between R and this existing third party javascript library.
