### ISSUE TITLE
Vertical blue line joining box to timeline disappears when data.frame also has type="background" values

### ISSUE THREAD

**Issue by pssguy** [daattali/timevis#8]
```
y <- structure(list(start = c("2013-07-01", "2013-05-19"), style = c("background: Ivory;", 
                                                                     "background: #FFFFFF;"), content = c("Reece James<br> Fee(m): 0<br> Starts: 0", 
                                                                                                          "Moyes"), type = c("box", "background"), end = c(NA, "2014-04-22"
                                                                                                          )), .Names = c("start", "style", "content", "type", "end"), row.names = 35:36, class = "data.frame")

timevis(y)
```
![image](https://cloud.githubusercontent.com/assets/2775918/17422848/b64e7aa6-5a6a-11e6-8651-e311b30416e2.png)

**Comment by daattali** [comment]
Haven't looked into this yet, but if you have 5 minutes, it'd be fruitful
to see if this is a problem on my end or by vis.js, by trying to do that in
Javascript

**Comment by pssguy** [comment]
LOL 5 weeks maybe. I have no js skills

**Comment by daattali** [comment]
I haven't tried this yet on a laptop but just from looking at that image, I
think I can guess the problem. I'm assuming that the colour red is
overwriting the blue line. Try instead of "red" using "rgba (255,0,0,0.1)"
(that means red but with 90% opacity). It that works then there's no bug :)

**Comment by daattali** [comment]
I just tried running what I said above, and it does indeed work

**Comment by pssguy** [comment]
Thanks You threw me at first on the "red", as I had used  #FFFFFF, white!
 Like the idea of rgba, especially for 'background type
