### ISSUE TITLE
Force update of input$mytime_selected 

### ISSUE THREAD

**Issue by balintba** [daattali/timevis#82]
Hello,

I would like to allow the user to programatically select some elements - based on some criteria - on the timeline using the setSelection(...) function. After selecting the elements, I would need the IDs, in order to be able to delete and modify these. But the input$mytime_selected does not get updated as it was indicated in the description. Is there a way to force this input to get updated?

Thanks!

Best regards,
Balazs

**Comment by balintba** [comment]
Many thanks! I will update my version and will give it a try.

**Comment by balintba** [comment]
Hello, I have reinstalled the package from cran, but the issue still persist. AKA, after programatic selection of elements the input$mytime_selected still does not update. Would you mind to comment on this? Many thanks in advance!

**Comment by daattali** [comment]
It's not on CRAN - you'll need to install the github version

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by balintba** [comment]
Ok! Many thanks, now it works fine!
