### ISSUE TITLE
Adding bar/area/line charts as part of timeline?

### ISSUE THREAD

**Issue by py** [daattali/timevis#84]
This package is great, however I would like to add a chart representing a variable (e.g. monthly population) above the timeline. This would require the addition of a y-axis and some plotting package that could re-render based on the zoom level (adjust bins, etc.). 

An extremely complicated example: http://www.odyeda.com/en/attachments/20160311_Jewish_Timeline_Odyeda_White.pdf

I understand this is a departure from the interactive timeline use case that this package manages well. Is `timevis` the right foundation for this kind of feature?

**Comment by daattali** [comment]
I don't think you can easily achieve this. You could add a chart above the timevis, but the two would not be connected (the x axes wouldn't scroll together). It's a very specialized type of graph that you'll likely need custom javascript/javascript libraries to create. Or you can try just having a chart and a timevis, separately, but I don't think that would look good. In any case, this is out of scope for timevis.
