### ISSUE TITLE
Switch of vertical lines

### ISSUE THREAD

**Issue by systats** [daattali/timevis#86]
Hi,

is there a way to switch off the vertical lines? 

![image](https://user-images.githubusercontent.com/22753281/67787698-4eb14680-fa71-11e9-8c0d-11aaaf499ee8.png)

It seems like they harm performance of the graphic if a lot of items are displayed.

Thanks in Advance!

**Comment by daattali** [comment]
You can look at visjs documentation to see if the library supports that, but I would imagine that there is no way to "turn them off". What you can do is hide them with CSS, or use your own custom javascript to delete them.
