### ISSUE TITLE
saveWidget(selfcontained=TRUE) renders the zoom menu in <pre> tags

### ISSUE THREAD

**Issue by rfaelens** [daattali/timevis#87]
Because of this, the following code fails, and setup of the timevis is not completed correctly:
https://github.com/daattali/timevis/blob/e354debbef257801e8a2b07930f7f7daabc4dc6a/inst/htmlwidgets/timevis.js#L33

A quick workaround would be to test the presence of the zoom menu, and only register these listeners if the menu exists.

**Comment by daattali** [comment]
This seems to me like a bug in htmlwidgets::saveWidget(), would you agree? If so, we should file this bug with htmlwidgets

**Comment by rfaelens** [comment]
OK, will file the bug with `htmlwidgets`

**Comment by daattali** [comment]
Please link to this issue, thanks!
