### ISSUE TITLE
Cannot specify order of stacked items

### ISSUE THREAD

**Issue by 27518** [daattali/timevis#89]
Hello Dean,
I am trying to order stacked items in the same order across all dates. I used the "order" function in the options section, but it's not working. I want to order alphabetically by the content. The data is from a dataframe that will change based on user selection in R Shiny. Can you please advise?

current code: 
output$hcc_i_timevis <- renderTimevis({
      timevis(data = data.frame(
              start = test$start_date,
              end = NA,
              content = test$content,
              group = rep("hcc", length(test$start_date))
              ),
        height = 400,
        options = list(order = test$content)
      )
    })

I can't figure out what is determining the order of the stacked items. The order I want appears in the first 3 but then changes after that.

**Comment by daattali** [comment]
Are you sure you're using the `order` parameter correctly? I've never tried using it (the timeline javascript library has tons of options and features, I only provide a way to use it from R, I haven't actually played around with all of them) but just from a quick read of the [docs](https://visjs.github.io/vis-timeline/docs/timeline/) it seems that `order` is meant to be a function, not a vector of values. I would first try to understand how that parameter works in javascript, and only then try to mirror it in the shiny package

**Comment by 27518** [comment]
Thanks for your response!  According to the docs: "The function order is called with two arguments containing the data of two items to be compared."  Unfortunately I can't figure out how to write a function that meets the criteria and will properly order my data since the items are all in one column so hard to compare 2 at a time. 

I'll close the issue since it's not actually an issue with the timevis package in R.
