### ISSUE TITLE
Upgrade to vis-timeline v6.4

### ISSUE THREAD

**Issue by vpanfilov** [daattali/timevis#91]
`v6.4.0` of **vis-timeline** has been released recently (https://github.com/visjs/vis-timeline/releases). Are there any plans for upgrading this package to v6 branch? Version 4 seems to be not maintained anymore.

**Comment by daattali** [comment]
I've looked several times in the past into upgrading, but every time I've tried, I found that the new version has some regression bugs so I decided not to upgrade.

https://github.com/daattali/timevis/issues/50

I've spent so many hours trying to integrate updated versions so many times that I've given up on doing it myself. If someone else would like to try to upgrade and make sure that there are no regressions, I would definitely appreciate that help with a pull request!

**Comment by daattali** [comment]
As mentioned in #50, I'll update once the regression bugs in visjs are resolved
