### ISSUE TITLE
Initial Zoom & Phases Within Dates

### ISSUE THREAD

**Issue by owbezick** [daattali/timevis#97]
A couple questions:
1.  Is it possible for to set an initial zoom level?
2. Is there a quick way to add different "phases" for the same events? For instance, having different colors for certain dates throughout a ranged item.  
Specifically for use within a shiny application.
Thank you!

**Comment by daattali** [comment]
I'm not sure if these features are supported or not. You would need to consult the documentation of visjs Timeline. This package is mostly a binding to that library.
